services:
  newshub:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_GUARDIAN_API_KEY: ${VITE_GUARDIAN_API_KEY}
        VITE_GUARDIAN_BASE_URL: ${VITE_GUARDIAN_BASE_URL}
        VITE_NYT_API_KEY: ${VITE_NYT_API_KEY}
        VITE_NYT_BASE_URL: ${VITE_NYT_BASE_URL}
        VITE_NEWSAPI_API_KEY: ${VITE_NEWSAPI_API_KEY}
        VITE_NEWSAPI_BASE_URL: ${VITE_NEWSAPI_BASE_URL}
    ports:
      - "3000:80"
